### ISSUE TITLE
Implementing custom data reader

### ISSUE THREAD

**Issue by staticfloat** [benmoran/TensorFlow.jl#2]
Hello @benmoran, I'm having a lot of fun exploring the ins and outs of your repository.  I am new to Tensorflow, but my project involves a lot of audio processing, so I think I need to write a new datasource.  Is the currently accepted way to do this to define a python class as you do in [`input_data.py`](https://github.com/benmoran/TensorFlow.jl/blob/370dab33c6a7a1eab7fb98ff2464698d335630d2/src/input_data.py#L95-L173), then [`@PyCall.pyimport` it](https://github.com/benmoran/TensorFlow.jl/blob/master/src/InputData.jl#L10)?  Or is there a way to do this from Julia as well?

**Comment by dmrd** [comment]
Check out `@pydef` in the [PyCall](https://github.com/stevengj/PyCall.jl) package (note that you will need master branch, as the current 1.4.0 release doesn't have it).  You can define a method in Julia that is then called on the Python side.  I've been using this to define a generator from the Julia side, but haven't tried it specifically for Tensorflow.  It's also unclear how this will affect performance.

Example:

```
# Simple infinite loop over given X
julia> @pydef type Generator
           __init__(self, X) = (self[:X] = X; self[:i] = 1)
           next(self) = begin
               i = self[:i]
               self[:i] = i % length(self[:X]) + 1
               return self[:X][i]
           end
       end
PyObject <class 'Generator'>

julia> pyeval("[next(x) for i in range(0,10)]", x=Generator([1,2,3,4,5]))
10-element Array{Any,1}:
 1
 2
 3
 4
 5
 1
 2
 3
 4
 5
```

I did something [similar as a data loader here](https://github.com/dmrd/go.jl/blob/generator/src/keras.jl#L132)

**Comment by staticfloat** [comment]
Very cool.  I'm running through this right now, but I just noticed that in the [`mnist` example](), you're not really using the `DataSet` class or its python equivalent at all with TensorFlow, you[ just pass TensorFlow numpy arrays](https://github.com/benmoran/TensorFlow.jl/blob/master/examples/mnist.jl#L72), right?  So if I were to manually load and create arrays in Julia of the appropriate shape, I don't need to mess around with `@pydef` or even Python at all.  Is that correct?

**Comment by staticfloat** [comment]
Yes, I got this working by not doing anything in python at all, but instead implementing everything in Julia and feeding my own objects in through the `FeedDict`.  I'll post an example eventually.
